version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Printf
        - fmt.Print
        - fmt.Println
  exclusions:
    paths:
      - docs
