# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AlpaconCli < Formula
  desc "Alpacon CLI"
  homepage "https://github.com/alpacax/alpacon-cli"
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/alpacax/alpacon-cli/releases/download/0.3.1/alpacon-0.3.1-darwin-amd64.tar.gz"
      sha256 "58c0e3fd355242ae2e3aab2bfc3cf0e4943c6bf53719e3e28a108aec27d9a5c3"

      def install
        bin.install "alpacon"
      end
    end
    on_arm do
      url "https://github.com/alpacax/alpacon-cli/releases/download/0.3.1/alpacon-0.3.1-darwin-arm64.tar.gz"
      sha256 "4fa9119f5c80136294acc543705642da55236ef64de9ec2a75d19db49e7d141a"

      def install
        bin.install "alpacon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/0.3.1/alpacon-0.3.1-linux-amd64.tar.gz"
        sha256 "d802f5d779168705ea86feaf1bd14b2bb9ab2bb882fb5a655ea2e0aec7efb8ee"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/0.3.1/alpacon-0.3.1-linux-arm.tar.gz"
        sha256 "66a45b37c87d5ccfcbeaab40ea7e87452099dc7bc027187710f9d45a55fb81fe"

        def install
          bin.install "alpacon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alpacax/alpacon-cli/releases/download/0.3.1/alpacon-0.3.1-linux-arm64.tar.gz"
        sha256 "c4d07a6e027ba646d526aa907f07d9a512348bec8bfe71cc21fc75e13ff35642"

        def install
          bin.install "alpacon"
        end
      end
    end
  end
end
